# Generated by Django 5.2.7 on 2026-02-28 18:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="api.company",
            ),
        ),
        migrations.CreateModel(
            name="SubTask",
            fields=[
                (
                    "subtaskID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("COMPLETE", "Complete"),
                            ("INCOMPLETE", "Incomplete"),
                        ],
                        default="INCOMPLETE",
                        max_length=20,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="api.task",
                    ),
                ),
            ],
        ),
    ]
