from django.contrib.auth.models import User
from rest_framework import serializers
from api.models import Task, Employee, Team, SubTask, Company


class RegisterSerializer(serializers.ModelSerializer):
    # These fields are for the User model
    password = serializers.CharField(write_only=True)
    first_name = serializers.CharField(required=False, allow_blank=True)
    last_name = serializers.CharField(required=False, allow_blank=True)

    # This field is for the Employee model
    company_id = serializers.UUIDField(write_only=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'first_name', 'last_name', 'company_id']

    def create(self, validated_data):
        # 1. Extract the data meant for the Employee/Company
        company_id = validated_data.pop('company_id')
        try:
            company = Company.objects.get(compID=company_id)
        except Company.DoesNotExist:
            raise serializers.ValidationError({"companyID": "Company not found"})

        # 2. Create the User
        user = User.objects.create_user(
            username=validated_data['username'],
            email=validated_data.get('email', ''),
            password=validated_data['password'],
            first_name=validated_data.get('first_name', ''),
            last_name=validated_data.get('last_name', '')
        )

        # 3. Find the Company and create the Employee
        try:
            company = Company.objects.get(compID=company_id)
        except Company.DoesNotExist:
            # If for some reason the company is missing, we still need to create the profile
            company = None

        # 4. Create the Employee
        employee = Employee.objects.create(
            user=user,
            company=company
        )

        # --- MINIMAL CHANGE START ---
        # Find the first team in that company to set as default
        if company:
            default_team = company.teams.first() # Or: Team.objects.filter(company=company, name="General").first()
            if default_team:
                employee.teams.add(default_team)
        # --- MINIMAL CHANGE END ---
        
        return user


class EmployeeListSerializer(serializers.ModelSerializer):
    # Mapping model fields to specific JSON keys with capitalization
    EmployeeID = serializers.UUIDField(source='employeeID')
    
    # Concatenating first and last name
    Name = serializers.SerializerMethodField()
    
    # Using get_position_display to get "Team Lead" instead of "LEAD"
    Position = serializers.CharField(source='get_position_display')
    
    # Pulling just the UUIDs of the teams into a list
    teamIDs = serializers.PrimaryKeyRelatedField(
        many=True, 
        read_only=True, 
        source='teams'
    )
    
    # Pulling the specific company UUID
    companyID = serializers.UUIDField(source='company.compID', allow_null=True)
    
    # Pulling email from the related User model
    email = serializers.EmailField(source='user.email')

    class Meta:
        model = Employee
        fields = ['EmployeeID', 'Name', 'Position', 'teamIDs', 'companyID', 'email']

    def get_Name(self, obj):
        # Combines first and last name, or falls back to username if names aren't set
        full_name = f"{obj.user.first_name} {obj.user.last_name}".strip()
        return full_name if full_name else obj.user.username


class TeamListSerializer(serializers.ModelSerializer):
    # Mapping to your requested JSON format
    teamID = serializers.UUIDField()
    Name = serializers.CharField(source='name')
    
    # Extract list of Task UUIDs
    TaskIDs = serializers.PrimaryKeyRelatedField(
        many=True, 
        read_only=True, 
        source='tasks'
    )
    
    # Extract the UUID from the related Company model
    compID = serializers.UUIDField(source='company.compID')
    
    # Extract the employeeID from the related Employee model
    leaderID = serializers.UUIDField(source='leader.employeeID', allow_null=True)

    class Meta:
        model = Team
        fields = ['teamID', 'Name', 'TaskIDs', 'compID', 'leaderID']

class TeamCreateSerializer(serializers.ModelSerializer):
    # Mapping PascalCase input to model fields
    Name = serializers.CharField(source='name')
    compID = serializers.PrimaryKeyRelatedField(
        queryset=Company.objects.all(), 
        source='company'
    )
    # leaderID is optional during creation
    leaderID = serializers.PrimaryKeyRelatedField(
        queryset=Employee.objects.all(), 
        source='leader', 
        required=False, 
        allow_null=True
    )

    class Meta:
        model = Team
        fields = ['Name', 'compID', 'leaderID']

    def create(self, validated_data):
        # teamID is auto-generated by the model (uuid4)
        return Team.objects.create(**validated_data)
